# Configuração do banco de dados Snorby
#
# Defina aqui seu usuario e senha
# NOTE: A indentação deve se manter!
#

snorby: &snorby
  adapter: mysql
  username: snorby
  password: "PASSWORD123" # Sua senha
  host: localhost


development:
  database: snorby
  <<: *snorby

test:
  database: snorby
  <<: *snorby

production:
  database: snorby
  <<: *snorby
